server:
  port: 8087

spring:
  application:
    name: LibrarySemiProject1

  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
      
  thymeleaf:
      cache: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update


  h2:
    console:
      enabled: true
      path: /h2-console
      
aladin:
  api:
    key: ttbdeer29771354001
